# Generated by Django 4.0.4 on 2022-06-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardFeeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(max_length=255)),
                ('describe', models.CharField(max_length=2500)),
                ('tglupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='quotesFelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hastegquotes', models.CharField(max_length=1000)),
                ('quotesdesc', models.CharField(max_length=1000)),
                ('quoteupdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
