# Generated by Django 4.0.4 on 2022-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Layanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='salery_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_salery', models.IntegerField()),
                ('name_file', models.CharField(max_length=1000)),
                ('json_file', models.JSONField()),
            ],
        ),
    ]
