# Generated by Django 4.0.4 on 2022-07-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Layanan', '0002_salery_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salery_data',
        ),
    ]
