# Generated by Django 4.0.4 on 2022-07-17 13:06

import Layanan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Layanan', '0003_delete_salery_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleryOfData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_salery', models.IntegerField(default=Layanan.models.SaleryOfData.number, unique=True)),
                ('Experience', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Salery', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
