# Generated by Django 4.0.4 on 2022-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Layanan', '0004_saleryofdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_json',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=200)),
                ('the_json', models.JSONField()),
            ],
        ),
    ]
