# Generated by Django 4.0.4 on 2022-08-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_images', models.CharField(max_length=500)),
                ('json_imagess', models.JSONField()),
            ],
        ),
    ]
